### ISSUE TITLE
InteractiveViwer Error

### ISSUE THREAD

**Issue by bawantha** [tkortekaas/pinch_zoom#5]
```
 Error: The method 'InteractiveViewer' isn't defined for the class '_PinchZoomState'.
 - '_PinchZoomState' is from 'package:pinch_zoom/src/pinch_zoom_widget.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pinch_zoom-0.0.3/lib/src/pinch_zoom_widget.dart').
Try correcting the name to the name of an existing method, or defining a method named 'InteractiveViewer'.
            child: InteractiveViewer(
```

**Comment by tkortekaas** [comment]
Could you run "flutter doctor -v" and then share the output here? Most likely this problem has to do with your Flutter version. This package is based on Flutter's InteractiveViewer widget and this widget has only recently been introduced in version 1.20. Therefore upgrading your Flutter version to 1.20 could resolve this issue straight away
